# Copyright (c) 2026 Adam Karpierz
# SPDX-License-Identifier: MIT

from __future__ import annotations

import typing
from typing import TYPE_CHECKING, TypeVar, TypeAlias
from collections.abc import Callable
import ctypes as ct

from utlx import ctypes as ctx

from ._platform import CFUNC
from ._dll      import dll

# ************************ #
# Section - ABI Versioning #
# ************************ #

# The latest ABI version that is supported by the current version of the
# library. When Languages are generated by the Tree-sitter CLI, they are
# assigned an ABI version number that corresponds to the current CLI version.
# The Tree-sitter library is generally backwards-compatible with languages
# generated using older CLI versions, but is not forwards-compatible.
#
TREE_SITTER_LANGUAGE_VERSION = 15

# The earliest ABI version that is supported by the current version of the
# library.
#
TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION = 13

# *************** #
# Section - Types #
# *************** #

TSStateId = ct.c_uint16
TSSymbol  = ct.c_uint16
TSFieldId = ct.c_uint16
class TSLanguage(ct.Structure): pass
class TSParser(ct.Structure): pass
class TSTree(ct.Structure): pass
class TSQuery(ct.Structure): pass
class TSQueryCursor(ct.Structure): pass
class TSLookaheadIterator(ct.Structure): pass

# This function signature reads one code point from the given string,
# returning the number of bytes consumed. It should write the code point
# to the `code_point` pointer, or write -1 if the input is invalid.
TSDecodeFunction = CFUNC(ct.c_uint32,
                         ct.POINTER(ct.c_uint8),  # string
                         ct.c_uint32,             # length
                         ct.POINTER(ct.c_int32))  # code_point
# Deprecated alias to be removed in ABI 16
DecodeFunction = TSDecodeFunction

TSInputEncoding = ct.c_int
(
    TSInputEncodingUTF8,
    TSInputEncodingUTF16LE,
    TSInputEncodingUTF16BE,
    TSInputEncodingCustom

) = range(0, 4)

TSSymbolType = ct.c_int
(
    TSSymbolTypeRegular,
    TSSymbolTypeAnonymous,
    TSSymbolTypeSupertype,
    TSSymbolTypeAuxiliary,

) = range(0, 4)

class TSPoint(ct.Structure):
    _fields_ = [
    ("row",    ct.c_uint32),
    ("column", ct.c_uint32),
]

class TSRange(ct.Structure):
    _fields_ = [
    ("start_point", TSPoint),
    ("end_point",   TSPoint),
    ("start_byte",  ct.c_uint32),
    ("end_byte",    ct.c_uint32),
]

class TSInput(ct.Structure):
    _fields_ = [
    ("payload",  ct.c_void_p),
    ("read",     CFUNC(ct.POINTER(ct.c_ubyte),
                       ct.c_void_p,                # payload
                       ct.c_uint32,                # byte_index
                       TSPoint,                    # position
                       ct.POINTER(ct.c_uint32))),  # bytes_read
    ("encoding", TSInputEncoding),
    ("decode",   TSDecodeFunction),
]

class TSParseState(ct.Structure):
    _fields_ = [
    ("payload",             ct.c_void_p),
    ("current_byte_offset", ct.c_uint32),
    ("has_error",           ct.c_bool),
]

class TSParseOptions(ct.Structure):
    _fields_ = [
    ("payload",           ct.c_void_p),
    ("progress_callback", CFUNC(ct.c_bool,
                                ct.POINTER(TSParseState))),  # state
]

TSLogType = ct.c_int
(
    TSLogTypeParse,
    TSLogTypeLex,

) = range(0, 2)

class TSLogger(ct.Structure):
    _fields_ = [
    ("payload", ct.c_void_p),
    ("log",     CFUNC(None,
                      ct.c_void_p,               # payload
                      TSLogType,                 # log_type
                      ct.POINTER(ct.c_ubyte))),  # buffer
]

# A summary of a change to a text document.
#
# The `start_byte` and `start_point` values must be less than or equal to the
# `old_end_byte` and `old_end_point` values, respectively. Passing an edit
# that violates these invariants may produce nonsensical results.
#
class TSInputEdit(ct.Structure):
    _fields_ = [
    ("start_byte",    ct.c_uint32),
    ("old_end_byte",  ct.c_uint32),
    ("new_end_byte",  ct.c_uint32),
    ("start_point",   TSPoint),
    ("old_end_point", TSPoint),
    ("new_end_point", TSPoint),
]

class TSNode(ct.Structure):
    _fields_ = [
    ("context", (ct.c_uint32 * 4)),
    ("id",      ct.c_void_p),
    ("tree",    ct.POINTER(TSTree)),
]

class TSTreeCursor(ct.Structure):
    _fields_ = [
    ("tree",    ct.c_void_p),
    ("id",      ct.c_void_p),
    ("context", (ct.c_uint32 * 3)),
]

class TSQueryCapture(ct.Structure):
    _fields_ = [
    ("node",  TSNode),
    ("index", ct.c_uint32),
]

TSQuantifier = ct.c_int
(
    TSQuantifierZero,  # = 0, # must match the array initialization value
    TSQuantifierZeroOrOne,
    TSQuantifierZeroOrMore,
    TSQuantifierOne,
    TSQuantifierOneOrMore,

) = range(0, 5)

class TSQueryMatch(ct.Structure):
    _fields_ = [
    ("id",            ct.c_uint32),
    ("pattern_index", ct.c_uint16),
    ("capture_count", ct.c_uint16),
    ("captures",      ct.POINTER(TSQueryCapture)),
]

TSQueryPredicateStepType = ct.c_int
(
    TSQueryPredicateStepTypeDone,
    TSQueryPredicateStepTypeCapture,
    TSQueryPredicateStepTypeString,

) = range(0, 3)

class TSQueryPredicateStep(ct.Structure):
    _fields_ = [
    ("type",     TSQueryPredicateStepType),
    ("value_id", ct.c_uint32),
]

TSQueryError = ct.c_int
(
    TSQueryErrorNone,  # = 0,
    TSQueryErrorSyntax,
    TSQueryErrorNodeType,
    TSQueryErrorField,
    TSQueryErrorCapture,
    TSQueryErrorStructure,
    TSQueryErrorLanguage,

) = range(0, 7)

class TSQueryCursorState(ct.Structure):
    _fields_ = [
    ("payload",             ct.c_void_p),
    ("current_byte_offset", ct.c_uint32),
]

class TSQueryCursorOptions(ct.Structure):
    _fields_ = [
    ("payload",           ct.c_void_p),
    ("progress_callback", CFUNC(ct.c_bool,
                                ct.POINTER(TSQueryCursorState))),  # state
]

# The metadata associated with a language.
#
# Currently, this metadata can be used to check the [Semantic Version](https://semver.org/)
# of the language. This version information should be used to signal if a given parser might
# be incompatible with existing queries when upgrading between major versions, or minor versions
# if it's in zerover.
#
class TSLanguageMetadata(ct.Structure):
    _fields_ = [
    ("major_version", ct.c_uint8),
    ("minor_version", ct.c_uint8),
    ("patch_version", ct.c_uint8),
]

# ****************** #
# Section - Parser #
# ****************** #

# Create a new parser.
#
parser_new = CFUNC(ct.POINTER(TSParser))(
    ("ts_parser_new", dll),)

# Delete the parser, freeing all of the memory that it used.
#
parser_delete = CFUNC(None,
    ct.POINTER(TSParser))(
    ("ts_parser_delete", dll), (
    (1, "self"),))

# Get the parser's current language.
#
parser_language = CFUNC(ct.POINTER(TSLanguage),
    ct.POINTER(TSParser))(
    ("ts_parser_language", dll), (
    (1, "self"),))

# Set the language that the parser should use for parsing.
#
# Returns a boolean indicating whether or not the language was successfully
# assigned. True means assignment succeeded. False means there was a version
# mismatch: the language was generated with an incompatible version of the
# Tree-sitter CLI. Check the language's ABI version using [`ts_language_abi_version`]
# and compare it to this library's [`TREE_SITTER_LANGUAGE_VERSION`] and
# [`TREE_SITTER_MIN_COMPATIBLE_LANGUAGE_VERSION`] constants.
#
parser_set_language = CFUNC(ct.c_bool,
    ct.POINTER(TSParser),
    ct.POINTER(TSLanguage))(
    ("ts_parser_set_language", dll), (
    (1, "self"),
    (1, "language"),))

# Set the ranges of text that the parser should include when parsing.
#
# By default, the parser will always include entire documents. This function
# allows you to parse only a *portion* of a document but still return a syntax
# tree whose ranges match up with the document as a whole. You can also pass
# multiple disjoint ranges.
#
# The second and third parameters specify the location and length of an array
# of ranges. The parser does *not* take ownership of these ranges; it copies
# the data, so it doesn't matter how these ranges are allocated.
#
# If `count` is zero, then the entire document will be parsed. Otherwise,
# the given ranges must be ordered from earliest to latest in the document,
# and they must not overlap. That is, the following must hold for all:
#
# `i < count - 1`: `ranges[i].end_byte <= ranges[i + 1].start_byte`
#
# If this requirement is not satisfied, the operation will fail, the ranges
# will not be assigned, and this function will return `false`. On success,
# this function returns `true`
#
parser_set_included_ranges = CFUNC(ct.c_bool,
    ct.POINTER(TSParser),
    ct.POINTER(TSRange),
    ct.c_uint32)(
    ("ts_parser_set_included_ranges", dll), (
    (1, "self"),
    (1, "ranges"),
    (1, "count"),))

# Get the ranges of text that the parser will include when parsing.
#
# The returned pointer is owned by the parser. The caller should not free it
# or write to it. The length of the array will be written to the given
# `count` pointer.
#
parser_included_ranges = CFUNC(ct.POINTER(TSRange),
    ct.POINTER(TSParser),
    ct.POINTER(ct.c_uint32))(
    ("ts_parser_included_ranges", dll), (
    (1, "self"),
    (1, "count"),))

# Use the parser to parse some source code and create a syntax tree.
#
# If you are parsing this document for the first time, pass `NULL` for the
# `old_tree` parameter. Otherwise, if you have already parsed an earlier
# version of this document and the document has since been edited, pass the
# previous syntax tree so that the unchanged parts of it can be reused.
# This will save time and memory. For this to work correctly, you must have
# already edited the old syntax tree using the [`ts_tree_edit`] function in a
# way that exactly matches the source code changes.
#
# The [`TSInput`] parameter lets you specify how to read the text. It has the
# following three fields:
# 1. [`read`]: A function to retrieve a chunk of text at a given byte offset
#    and (row, column) position. The function should return a pointer to the
#    text and write its length to the [`bytes_read`] pointer. The parser does
#    not take ownership of this buffer; it just borrows it until it has
#    finished reading it. The function should write a zero value to the
#    [`bytes_read`] pointer to indicate the end of the document.
# 2. [`payload`]: An arbitrary pointer that will be passed to each invocation
#    of the [`read`] function.
# 3. [`encoding`]: An indication of how the text is encoded. Either
#    `TSInputEncodingUTF8` or `TSInputEncodingUTF16`.
#
# This function returns a syntax tree on success, and `NULL` on failure. There
# are four possible reasons for failure:
# 1. The parser does not have a language assigned. Check for this using the
#    [`ts_parser_language`] function.
# 2. Parsing was cancelled due to the progress callback returning true. This callback
#    is passed in [`ts_parser_parse_with_options`] inside the [`TSParseOptions`] struct.
#
# [`read`]: TSInput::read
# [`payload`]: TSInput::payload
# [`encoding`]: TSInput::encoding
# [`bytes_read`]: TSInput::read
#
parser_parse = CFUNC(ct.POINTER(TSTree),
    ct.POINTER(TSParser),
    ct.POINTER(TSTree),
    TSInput)(
    ("ts_parser_parse", dll), (
    (1, "self"),
    (1, "old_tree"),
    (1, "input"),))

# Use the parser to parse some source code and create a syntax tree, with some options.
#
# See [`ts_parser_parse`] for more details.
#
# See [`TSParseOptions`] for more details on the options.
#
parser_parse_with_options = CFUNC(ct.POINTER(TSTree),
    ct.POINTER(TSParser),
    ct.POINTER(TSTree),
    TSInput,
    TSParseOptions)(
    ("ts_parser_parse_with_options", dll), (
    (1, "self"),
    (1, "old_tree"),
    (1, "input"),
    (1, "parse_options"),))

# Use the parser to parse some source code stored in one contiguous buffer.
# The first two parameters are the same as in the [`ts_parser_parse`] function
# above. The second two parameters indicate the location of the buffer and its
# length in bytes.
#
parser_parse_string = CFUNC(ct.POINTER(TSTree),
    ct.POINTER(TSParser),
    ct.POINTER(TSTree),
    ct.POINTER(ct.c_ubyte),
    ct.c_uint32)(
    ("ts_parser_parse_string", dll), (
    (1, "self"),
    (1, "old_tree"),
    (1, "string"),
    (1, "length"),))

# Use the parser to parse some source code stored in one contiguous buffer with
# a given encoding. The first four parameters work the same as in the
# [`ts_parser_parse_string`] method above. The final parameter indicates whether
# the text is encoded as UTF8 or UTF16.
#
parser_parse_string_encoding = CFUNC(ct.POINTER(TSTree),
    ct.POINTER(TSParser),
    ct.POINTER(TSTree),
    ct.POINTER(ct.c_ubyte),
    ct.c_uint32,
    TSInputEncoding)(
    ("ts_parser_parse_string_encoding", dll), (
    (1, "self"),
    (1, "old_tree"),
    (1, "string"),
    (1, "length"),
    (1, "encoding"),))

# Instruct the parser to start the next parse from the beginning.
#
# If the parser previously failed because of the progress callback, then
# by default, it will resume where it left off on the next call to
# [`ts_parser_parse`] or other parsing functions. If you don't want to resume,
# and instead intend to use this parser to parse some other document, you must
# call [`ts_parser_reset`] first.
#
parser_reset = CFUNC(None,
    ct.POINTER(TSParser))(
    ("ts_parser_reset", dll), (
    (1, "self"),))

# Set the logger that a parser should use during parsing.
#
# The parser does not take ownership over the logger payload. If a logger was
# previously assigned, the caller is responsible for releasing any memory
# owned by the previous logger.
#
parser_set_logger = CFUNC(None,
    ct.POINTER(TSParser),
    TSLogger)(
    ("ts_parser_set_logger", dll), (
    (1, "self"),
    (1, "logger"),))

# Get the parser's current logger.
#
parser_logger = CFUNC(TSLogger,
    ct.POINTER(TSParser))(
    ("ts_parser_logger", dll), (
    (1, "self"),))

# Set the file descriptor to which the parser should write debugging graphs
# during parsing. The graphs are formatted in the DOT language. You may want
# to pipe these graphs directly to a `dot(1)` process in order to generate
# SVG output. You can turn off this logging by passing a negative number.
#
parser_print_dot_graphs = CFUNC(None,
    ct.POINTER(TSParser),
    ct.c_int)(
    ("ts_parser_print_dot_graphs", dll), (
    (1, "self"),
    (1, "fd"),))

# ************** #
# Section - Tree #
# ************** #

# Create a shallow copy of the syntax tree. This is very fast.
#
# You need to copy a syntax tree in order to use it on more than one thread at
# a time, as syntax trees are not thread safe.
#
tree_delete = CFUNC(ct.POINTER(TSTree),
    ct.POINTER(TSTree))(
    ("ts_tree_copy", dll), (
    (1, "self"),))

# Delete the syntax tree, freeing all of the memory that it used.
#
tree_delete = CFUNC(None,
    ct.POINTER(TSTree))(
    ("ts_tree_delete", dll), (
    (1, "self"),))

# Get the root node of the syntax tree.
#
tree_root_node = CFUNC(TSNode,
    ct.POINTER(TSTree))(
    ("ts_tree_root_node", dll), (
    (1, "self"),))

# Get the root node of the syntax tree, but with its position
# shifted forward by the given offset.
#
tree_root_node_with_offset = CFUNC(TSNode,
    ct.POINTER(TSTree),
    ct.c_uint32,
    TSPoint)(
    ("ts_tree_root_node_with_offset", dll), (
    (1, "self"),
    (1, "offset_bytes"),
    (1, "offset_extent"),))

# Get the language that was used to parse the syntax tree.
#
tree_language = CFUNC(ct.POINTER(TSLanguage),
    ct.POINTER(TSTree))(
    ("ts_tree_language", dll), (
    (1, "self"),))

# Get the array of included ranges that was used to parse the syntax tree.
#
# The returned pointer must be freed by the caller.
#
tree_included_ranges = CFUNC(ct.POINTER(TSRange),
    ct.POINTER(TSTree),
    ct.POINTER(ct.c_uint32))(
    ("ts_tree_included_ranges", dll), (
    (1, "self"),
    (1, "length"),))

# Edit the syntax tree to keep it in sync with source code that has been
# edited.
#
# You must describe the edit both in terms of byte offsets and in terms of
# (row, column) coordinates.
#
# The edit's `start_byte` must be less than or equal to its `old_end_byte`,
# and its `start_point` must be less than or equal to its `old_end_point`.
#
tree_edit = CFUNC(None,
    ct.POINTER(TSTree),
    ct.POINTER(TSInputEdit))(
    ("ts_tree_edit", dll), (
    (1, "self"),
    (1, "edit"),))

# Compare an old edited syntax tree to a new syntax tree representing the same
# document, returning an array of ranges whose syntactic structure has changed.
#
# For this to work correctly, the old syntax tree must have been edited such
# that its ranges match up to the new tree. Generally, you'll want to call
# this function right after calling one of the [`ts_parser_parse`] functions.
# You need to pass the old tree that was passed to parse, as well as the new
# tree that was returned from that function.
#
# The returned ranges indicate areas where the hierarchical structure of syntax
# nodes (from root to leaf) has changed between the old and new trees. Characters
# outside these ranges have identical ancestor nodes in both trees.
#
# Note that the returned ranges may be slightly larger than the exact changed areas,
# but Tree-sitter attempts to make them as small as possible.
#
# The returned array is allocated using `malloc` and the caller is responsible
# for freeing it using `free`. The length of the array will be written to the
# given `length` pointer.
#
tree_get_changed_ranges = CFUNC(ct.POINTER(TSRange),
    ct.POINTER(TSTree),
    ct.POINTER(TSTree),
    ct.POINTER(ct.c_uint32))(
    ("ts_tree_get_changed_ranges", dll), (
    (1, "old_tree"),
    (1, "new_tree"),
    (1, "length"),))

# Write a DOT graph describing the syntax tree to the given file.
#
tree_print_dot_graph = CFUNC(None,
    ct.POINTER(TSTree),
    ct.c_int)(
    ("ts_tree_print_dot_graph", dll), (
    (1, "self"),
    (1, "file_descriptor"),))

# ************** #
# Section - Node #
# ************** #

# Get the node's type as a null-terminated string.
#
node_type = CFUNC(ct.c_char_p,
    TSNode)(
    ("ts_node_type", dll), (
    (1, "self"),))

# Get the node's type as a numerical id.
#
node_symbol = CFUNC(TSSymbol,
    TSNode)(
    ("ts_node_symbol", dll), (
    (1, "self"),))

# Get the node's language.
#
node_language = CFUNC(ct.POINTER(TSLanguage),
    TSNode)(
    ("ts_node_language", dll), (
    (1, "self"),))

# Get the node's type as it appears in the grammar ignoring aliases as a
# null-terminated string.
#
node_grammar_type = CFUNC(ct.c_char_p,
    TSNode)(
    ("ts_node_grammar_type", dll), (
    (1, "self"),))

# Get the node's type as a numerical id as it appears in the grammar ignoring
# aliases. This should be used in [`ts_language_next_state`] instead of
# [`ts_node_symbol`].
#
node_grammar_symbol = CFUNC(TSSymbol,
    TSNode)(
    ("ts_node_grammar_symbol", dll), (
    (1, "self"),))

# Get the node's start byte.
#
node_start_byte = CFUNC(ct.c_uint32,
    TSNode)(
    ("ts_node_start_byte", dll), (
    (1, "self"),))

# Get the node's start position in terms of rows and columns.
#
node_start_point = CFUNC(TSPoint,
    TSNode)(
    ("ts_node_start_point", dll), (
    (1, "self"),))

# Get the node's end byte.
#
node_end_byte = CFUNC(ct.c_uint32,
    TSNode)(
    ("ts_node_end_byte", dll), (
    (1, "self"),))

# Get the node's end position in terms of rows and columns.
#
node_end_point = CFUNC(TSPoint,
    TSNode)(
    ("ts_node_end_point", dll), (
    (1, "self"),))

# Get an S-expression representing the node as a string.
#
# This string is allocated with `malloc` and the caller is responsible for
# freeing it using `free`.
#
node_string = CFUNC(ct.c_char_p,  # char *,
    TSNode)(
    ("ts_node_string", dll), (
    (1, "self"),))

# Check if the node is null. Functions like [`ts_node_child`] and
# [`ts_node_next_sibling`] will return a null node to indicate that no such node
# was found.
#
node_is_null = CFUNC(ct.c_bool,
    TSNode)(
    ("ts_node_is_null", dll), (
    (1, "self"),))

# Check if the node is *named*. Named nodes correspond to named rules in the
# grammar, whereas *anonymous* nodes correspond to string literals in the
# grammar.
#
node_is_named = CFUNC(ct.c_bool,
    TSNode)(
    ("ts_node_is_named", dll), (
    (1, "self"),))

# Check if the node is *missing*. Missing nodes are inserted by the parser in
# order to recover from certain kinds of syntax errors.
#
node_is_missing = CFUNC(ct.c_bool,
    TSNode)(
    ("ts_node_is_missing", dll), (
    (1, "self"),))

# Check if the node is *extra*. Extra nodes represent things like comments,
# which are not required the grammar, but can appear anywhere.
#
node_is_extra = CFUNC(ct.c_bool,
    TSNode)(
    ("ts_node_is_extra", dll), (
    (1, "self"),))

# Check if a syntax node has been edited.
#
node_has_changes = CFUNC(ct.c_bool,
    TSNode)(
    ("ts_node_has_changes", dll), (
    (1, "self"),))

# Check if the node is a syntax error or contains any syntax errors.
#
node_has_error = CFUNC(ct.c_bool,
    TSNode)(
    ("ts_node_has_error", dll), (
    (1, "self"),))

# Check if the node is a syntax error.
#
node_is_error = CFUNC(ct.c_bool,
    TSNode)(
    ("ts_node_is_error", dll), (
    (1, "self"),))

# Get this node's parse state.
#
node_parse_state = CFUNC(TSStateId,
    TSNode)(
    ("ts_node_parse_state", dll), (
    (1, "self"),))

# Get the parse state after this node.
#
node_next_parse_state = CFUNC(TSStateId,
    TSNode)(
    ("ts_node_next_parse_state", dll), (
    (1, "self"),))

# Get the node's immediate parent.
# Prefer [`ts_node_child_with_descendant`] for
# iterating over the node's ancestors.
#
node_parent = CFUNC(TSNode,
    TSNode)(
    ("ts_node_parent", dll), (
    (1, "self"),))

# Get the node that contains `descendant`.
#
# Note that this can return `descendant` itself.
#
node_child_with_descendant = CFUNC(TSNode,
    TSNode,
    TSNode)(
    ("ts_node_child_with_descendant", dll), (
    (1, "self"),
    (1, "descendant"),))

# Get the node's child at the given index, where zero represents the first
# child.
#
node_child = CFUNC(TSNode,
    TSNode,
    ct.c_uint32)(
    ("ts_node_child", dll), (
    (1, "self"),
    (1, "child_index"),))

# Get the field name for node's child at the given index, where zero represents
# the first child. Returns NULL, if no field is found.
#
node_field_name_for_child = CFUNC(ct.c_char_p,
    TSNode,
    ct.c_uint32)(
    ("ts_node_field_name_for_child", dll), (
    (1, "self"),
    (1, "child_index"),))

# Get the field name for node's named child at the given index, where zero
# represents the first named child. Returns NULL, if no field is found.
#
node_field_name_for_named_child = CFUNC(ct.c_char_p,
    TSNode,
    ct.c_uint32)(
    ("ts_node_field_name_for_named_child", dll), (
    (1, "self"),
    (1, "named_child_index"),))

# Get the node's number of children.
#
node_child_count = CFUNC(ct.c_uint32,
    TSNode)(
    ("ts_node_child_count", dll), (
    (1, "self"),))

# Get the node's *named* child at the given index.
#
# See also [`ts_node_is_named`].
#
node_named_child = CFUNC(TSNode,
    TSNode,
    ct.c_uint32)(
    ("ts_node_named_child", dll), (
    (1, "self"),
    (1, "child_index"),))

# Get the node's number of *named* children.
#
# See also [`ts_node_is_named`].
#
node_named_child_count = CFUNC(ct.c_uint32,
    TSNode)(
    ("ts_node_named_child_count", dll), (
    (1, "self"),))

# Get the node's child with the given field name.
#
node_child_by_field_name = CFUNC(TSNode,
    TSNode,
    ct.POINTER(ct.c_ubyte),
    ct.c_uint32)(
    ("ts_node_child_by_field_name", dll), (
    (1, "self"),
    (1, "name"),
    (1, "name_length"),))

# Get the node's child with the given numerical field id.
#
# You can convert a field name to an id using the
# [`ts_language_field_id_for_name`] function.
#
node_child_by_field_id = CFUNC(TSNode,
    TSNode,
    TSFieldId)(
    ("ts_node_child_by_field_id", dll), (
    (1, "self"),
    (1, "field_id"),))

# Get the node's next / previous sibling.
#
node_next_sibling = CFUNC(TSNode,
    TSNode)(
    ("ts_node_next_sibling", dll), (
    (1, "self"),))
node_prev_sibling = CFUNC(TSNode,
    TSNode)(
    ("ts_node_prev_sibling", dll), (
    (1, "self"),))

# Get the node's next / previous *named* sibling.
#
node_next_named_sibling = CFUNC(TSNode,
    TSNode)(
    ("ts_node_next_named_sibling", dll), (
    (1, "self"),))
node_prev_named_sibling = CFUNC(TSNode,
    TSNode)(
    ("ts_node_prev_named_sibling", dll), (
    (1, "self"),))

# Get the node's first child that contains or starts after the given byte offset.
#
node_first_child_for_byte = CFUNC(TSNode,
    TSNode,
    ct.c_uint32)(
    ("ts_node_first_child_for_byte", dll), (
    (1, "self"),
    (1, "byte"),))

# Get the node's first named child that contains or starts after the given byte offset.
#
node_first_named_child_for_byte = CFUNC(TSNode,
    TSNode,
    ct.c_uint32)(
    ("ts_node_first_named_child_for_byte", dll), (
    (1, "self"),
    (1, "byte"),))

# Get the node's number of descendants, including one for the node itself.
#
node_descendant_count = CFUNC(ct.c_uint32,
    TSNode)(
    ("ts_node_descendant_count", dll), (
    (1, "self"),))

# Get the smallest node within this node that spans the given range of bytes
# or (row, column) positions.
#
node_descendant_for_byte_range = CFUNC(TSNode,
    TSNode,
    ct.c_uint32 ,
    ct.c_uint32)(
    ("ts_node_descendant_for_byte_range", dll), (
    (1, "self"),
    (1, "start"),
    (1, "end"),))
node_descendant_for_point_range = CFUNC(TSNode,
    TSNode,
    TSPoint,
    TSPoint)(
    ("ts_node_descendant_for_point_range", dll), (
    (1, "self"),
    (1, "start"),
    (1, "end"),))

# Get the smallest named node within this node that spans the given range of
# bytes or (row, column) positions.
#
node_named_descendant_for_byte_range = CFUNC(TSNode,
    TSNode,
    ct.c_uint32 ,
    ct.c_uint32)(
    ("ts_node_named_descendant_for_byte_range", dll), (
    (1, "self"),
    (1, "start"),
    (1, "end"),))
node_named_descendant_for_point_range = CFUNC(TSNode,
    TSNode,
    TSPoint,
    TSPoint)(
    ("ts_node_named_descendant_for_point_range", dll), (
    (1, "self"),
    (1, "start"),
    (1, "end"),))

# Edit the node to keep it in-sync with source code that has been edited.
#
# This function is only rarely needed. When you edit a syntax tree with the
# [`ts_tree_edit`] function, all of the nodes that you retrieve from the tree
# afterward will already reflect the edit. You only need to use [`ts_node_edit`]
# when you have a [`TSNode`] instance that you want to keep and continue to use
# after an edit.
#
# The edit's `start_byte` must be less than or equal to its `old_end_byte`,
# and its `start_point` must be less than or equal to its `old_end_point`.
#
node_edit = CFUNC(None,
    ct.POINTER(TSNode),
    ct.POINTER(TSInputEdit))(
    ("ts_node_edit", dll), (
    (1, "self"),
    (1, "edit"),))

# Check if two nodes are identical.
#
node_eq = CFUNC(ct.c_bool,
    TSNode,
    TSNode)(
    ("ts_node_eq", dll), (
    (1, "self"),
    (1, "other"),))

# Edit a point to keep it in-sync with source code that has been edited.
#
# This function updates a single point's byte offset and row/column position
# based on an edit operation. This is useful for editing points without
# requiring a tree or node instance.
#
# The edit's `start_byte` must be less than or equal to its `old_end_byte`,
# and its `start_point` must be less than or equal to its `old_end_point`.
#
point_edit = CFUNC(None,
    ct.POINTER(TSPoint),
    ct.POINTER(ct.c_uint32),
    ct.POINTER(TSInputEdit))(
    ("ts_point_edit", dll), (
    (1, "self"),
    (1, "point_byte"),
    (1, "edit"),))

# Edit a range to keep it in-sync with source code that has been edited.
#
# This function updates a range's start and end positions based on an edit
# operation. This is useful for editing ranges without requiring a tree
# or node instance.
#
# The edit's `start_byte` must be less than or equal to its `old_end_byte`,
# and its `start_point` must be less than or equal to its `old_end_point`.
#
range_edit = CFUNC(None,
    ct.POINTER(TSRange),
    ct.POINTER(TSInputEdit))(
    ("ts_range_edit", dll), (
    (1, "self"),
    (1, "edit"),))

# ******************** #
# Section - TreeCursor #
# ******************** #

# Create a new tree cursor starting from the given node.
#
# A tree cursor allows you to walk a syntax tree more efficiently than is
# possible using the [`TSNode`] functions. It is a mutable object that is always
# on a certain syntax node, and can be moved imperatively to different nodes.
#
# Note that the given node is considered the root of the cursor,
# and the cursor cannot walk outside this node.
#
tree_cursor_new = CFUNC(TSTreeCursor,
    TSNode)(
    ("ts_tree_cursor_new", dll), (
    (1, "node"),))

# Delete a tree cursor, freeing all of the memory that it used.
#
tree_cursor_delete = CFUNC(None,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_delete", dll), (
    (1, "self"),))

# Re-initialize a tree cursor to start at the original node that the cursor was
# constructed with.
#
tree_cursor_reset = CFUNC(None,
    ct.POINTER(TSTreeCursor),
    TSNode)(
    ("ts_tree_cursor_reset", dll), (
    (1, "self"),
    (1, "node"),))

# Re-initialize a tree cursor to the same position as another cursor.
#
# Unlike [`ts_tree_cursor_reset`], this will not lose parent information and
# allows reusing already created cursors.
#
tree_cursor_reset_to = CFUNC(None,
    ct.POINTER(TSTreeCursor),
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_reset_to", dll), (
    (1, "self"),
    (1, "src"),))

# Get the tree cursor's current node.
#
tree_cursor_current_node = CFUNC(TSNode,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_current_node", dll), (
    (1, "self"),))

# Get the field name of the tree cursor's current node.
#
# This returns `NULL` if the current node doesn't have a field.
# See also [`ts_node_child_by_field_name`].
#
tree_cursor_current_field_name = CFUNC(ct.c_char_p,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_current_field_name", dll), (
    (1, "self"),))

# Get the field id of the tree cursor's current node.
#
# This returns zero if the current node doesn't have a field.
# See also [`ts_node_child_by_field_id`], [`ts_language_field_id_for_name`].
#
tree_cursor_current_field_id = CFUNC(TSFieldId,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_current_field_id", dll), (
    (1, "self"),))

# Move the cursor to the parent of its current node.
#
# This returns `true` if the cursor successfully moved, and returns `false`
# if there was no parent node (the cursor was already on the root node).
#
# Note that the node the cursor was constructed with is considered the root
# of the cursor, and the cursor cannot walk outside this node.
#
tree_cursor_goto_parent = CFUNC(ct.c_bool,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_goto_parent", dll), (
    (1, "self"),))

# Move the cursor to the next sibling of its current node.
#
# This returns `true` if the cursor successfully moved, and returns `false`
# if there was no next sibling node.
#
# Note that the node the cursor was constructed with is considered the root
# of the cursor, and the cursor cannot walk outside this node.
#
tree_cursor_goto_next_sibling = CFUNC(ct.c_bool,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_goto_next_sibling", dll), (
    (1, "self"),))

# Move the cursor to the previous sibling of its current node.
#
# This returns `true` if the cursor successfully moved, and returns `false` if
# there was no previous sibling node.
#
# Note, that this function may be slower than
# [`ts_tree_cursor_goto_next_sibling`] due to how node positions are stored. In
# the worst case, this will need to iterate through all the children up to the
# previous sibling node to recalculate its position. Also note that the node the cursor
# was constructed with is considered the root of the cursor, and the cursor cannot
# walk outside this node.
#
tree_cursor_goto_previous_sibling = CFUNC(ct.c_bool,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_goto_previous_sibling", dll), (
    (1, "self"),))

# Move the cursor to the first child of its current node.
#
# This returns `true` if the cursor successfully moved, and returns `false`
# if there were no children.
#
tree_cursor_goto_first_child = CFUNC(ct.c_bool,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_goto_first_child", dll), (
    (1, "self"),))

# Move the cursor to the last child of its current node.
#
# This returns `true` if the cursor successfully moved, and returns `false` if
# there were no children.
#
# Note that this function may be slower than [`ts_tree_cursor_goto_first_child`]
# because it needs to iterate through all the children to compute the child's
# position.
#
tree_cursor_goto_last_child = CFUNC(ct.c_bool,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_goto_last_child", dll), (
    (1, "self"),))

# Move the cursor to the node that is the nth descendant of
# the original node that the cursor was constructed with, where
# zero represents the original node itself.
#
tree_cursor_goto_descendant = CFUNC(None,
    ct.POINTER(TSTreeCursor),
    ct.c_uint32)(
    ("ts_tree_cursor_goto_descendant", dll), (
    (1, "self"),
    (1, "goal_descendant_index"),))

# Get the index of the cursor's current node out of all of the
# descendants of the original node that the cursor was constructed with.
#
tree_cursor_current_descendant_index = CFUNC(ct.c_uint32,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_current_descendant_index", dll), (
    (1, "self"),))

# Get the depth of the cursor's current node relative to the original
# node that the cursor was constructed with.
#
tree_cursor_current_depth = CFUNC(ct.c_uint32,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_current_depth", dll), (
    (1, "self"),))

# Move the cursor to the first child of its current node that contains or starts after
# the given byte offset or point.
#
# This returns the index of the child node if one was found, and returns -1
# if no such child was found.
#
tree_cursor_goto_first_child_for_byte = CFUNC(ct.c_int64,
    ct.POINTER(TSTreeCursor),
    ct.c_uint32)(
    ("ts_tree_cursor_goto_first_child_for_byte", dll), (
    (1, "self"),
    (1, "goal_byte"),))
tree_cursor_goto_first_child_for_point = CFUNC(ct.c_int64,
    ct.POINTER(TSTreeCursor),
    TSPoint)(
    ("ts_tree_cursor_goto_first_child_for_point", dll), (
    (1, "self"),
    (1, "goal_point"),))

tree_cursor_copy = CFUNC(TSTreeCursor,
    ct.POINTER(TSTreeCursor))(
    ("ts_tree_cursor_copy", dll), (
    (1, "self"),))

# *************** #
# Section - Query #
# *************** #

# Create a new query from a string containing one or more S-expression
# patterns. The query is associated with a particular language, and can
# only be run on syntax nodes parsed with that language.
#
# If all of the given patterns are valid, this returns a [`TSQuery`].
# If a pattern is invalid, this returns `NULL`, and provides two pieces
# of information about the problem:
# 1. The byte offset of the error is written to the `error_offset` parameter.
# 2. The type of error is written to the `error_type` parameter.
#
query_new = CFUNC(ct.POINTER(TSQuery),
    ct.POINTER(TSLanguage),
    ct.POINTER(ct.c_ubyte),
    ct.c_uint32,
    ct.POINTER(ct.c_uint32),
    ct.POINTER(TSQueryError))(
    ("ts_query_new", dll), (
    (1, "language"),
    (1, "source"),
    (1, "source_len"),
    (1, "error_offset"),
    (1, "error_type"),))

# Delete a query, freeing all of the memory that it used.
#
query_delete = CFUNC(None,
    ct.POINTER(TSQuery))(
    ("ts_query_delete", dll), (
    (1, "self"),))

# Get the number of patterns, captures, or string literals in the query.
#
query_pattern_count = CFUNC(ct.c_uint32,
    ct.POINTER(TSQuery))(
    ("ts_query_pattern_count", dll), (
    (1, "self"),))
query_capture_count = CFUNC(ct.c_uint32,
    ct.POINTER(TSQuery))(
    ("ts_query_capture_count", dll), (
    (1, "self"),))
query_string_count = CFUNC(ct.c_uint32,
    ct.POINTER(TSQuery))(
    ("ts_query_string_count", dll), (
    (1, "self"),))

# Get the byte offset where the given pattern starts in the query's source.
#
# This can be useful when combining queries by concatenating their source
# code strings.
#
query_start_byte_for_pattern = CFUNC(ct.c_uint32,
    ct.POINTER(TSQuery),
    ct.c_uint32)(
    ("ts_query_start_byte_for_pattern", dll), (
    (1, "self"),
    (1, "pattern_index"),))

# Get the byte offset where the given pattern ends in the query's source.
#
# This can be useful when combining queries by concatenating their source
# code strings.
#
query_end_byte_for_pattern = CFUNC(ct.c_uint32,
    ct.POINTER(TSQuery),
    ct.c_uint32)(
    ("ts_query_end_byte_for_pattern", dll), (
    (1, "self"),
    (1, "pattern_index"),))

# Get all of the predicates for the given pattern in the query.
#
# The predicates are represented as a single array of steps. There are three
# types of steps in this array, which correspond to the three legal values for
# the `type` field:
# - `TSQueryPredicateStepTypeCapture` - Steps with this type represent names
#    of captures. Their `value_id` can be used with the
#   [`ts_query_capture_name_for_id`] function to obtain the name of the capture.
# - `TSQueryPredicateStepTypeString` - Steps with this type represent literal
#    strings. Their `value_id` can be used with the
#    [`ts_query_string_value_for_id`] function to obtain their string value.
# - `TSQueryPredicateStepTypeDone` - Steps with this type are *sentinels*
#    that represent the end of an individual predicate. If a pattern has two
#    predicates, then there will be two steps with this `type` in the array.
#
query_predicates_for_pattern = CFUNC(ct.POINTER(TSQueryPredicateStep),
    ct.POINTER(TSQuery),
    ct.c_uint32,
    ct.POINTER(ct.c_uint32))(
    ("ts_query_predicates_for_pattern", dll), (
    (1, "self"),
    (1, "pattern_index"),
    (1, "step_count"),))

# Check if the given pattern in the query has a single root node.
#
query_is_pattern_rooted = CFUNC(ct.c_bool,
    ct.POINTER(TSQuery),
    ct.c_uint32)(
    ("ts_query_is_pattern_rooted", dll), (
    (1, "self"),
    (1, "pattern_index"),))

# Check if the given pattern in the query is 'non local'.
#
# A non-local pattern has multiple root nodes and can match within a
# repeating sequence of nodes, as specified by the grammar. Non-local
# patterns disable certain optimizations that would otherwise be possible
# when executing a query on a specific range of a syntax tree.
#
query_is_pattern_non_local = CFUNC(ct.c_bool,
    ct.POINTER(TSQuery),
    ct.c_uint32)(
    ("ts_query_is_pattern_non_local", dll), (
    (1, "self"),
    (1, "pattern_index"),))

# Check if a given pattern is guaranteed to match once a given step is reached.
# The step is specified by its byte offset in the query's source code.
#
query_is_pattern_guaranteed_at_step = CFUNC(ct.c_bool,
    ct.POINTER(TSQuery),
    ct.c_uint32)(
    ("ts_query_is_pattern_guaranteed_at_step", dll), (
    (1, "self"),
    (1, "byte_offset"),))

# Get the name and length of one of the query's captures, or one of the
# query's string literals. Each capture and string is associated with a
# numeric id based on the order that it appeared in the query's source.
#
query_capture_name_for_id = CFUNC(ct.POINTER(ct.c_ubyte),
    ct.POINTER(TSQuery),
    ct.c_uint32,
    ct.POINTER(ct.c_uint32))(
    ("ts_query_capture_name_for_id", dll), (
    (1, "self"),
    (1, "index"),
    (1, "length"),))

# Get the quantifier of the query's captures. Each capture is * associated
# with a numeric id based on the order that it appeared in the query's source.
#
query_capture_quantifier_for_id = CFUNC(TSQuantifier,
    ct.POINTER(TSQuery),
    ct.c_uint32,
    ct.c_uint32)(
    ("ts_query_capture_quantifier_for_id", dll), (
    (1, "self"),
    (1, "pattern_index"),
    (1, "capture_index"),))

query_string_value_for_id = CFUNC(ct.POINTER(ct.c_ubyte),
    ct.POINTER(TSQuery),
    ct.c_uint32,
    ct.POINTER(ct.c_uint32))(
    ("ts_query_string_value_for_id", dll), (
    (1, "self"),
    (1, "index"),
    (1, "length"),))

# Disable a certain capture within a query.
#
# This prevents the capture from being returned in matches, and also avoids
# any resource usage associated with recording the capture. Currently, there
# is no way to undo this.
#
query_disable_capture = CFUNC(None,
    ct.POINTER(TSQuery),
    ct.POINTER(ct.c_ubyte),
    ct.c_uint32)(
    ("ts_query_disable_capture", dll), (
    (1, "self"),
    (1, "name"),
    (1, "length"),))

# Disable a certain pattern within a query.
#
# This prevents the pattern from matching and removes most of the overhead
# associated with the pattern. Currently, there is no way to undo this.
#
query_disable_pattern = CFUNC(None,
    ct.POINTER(TSQuery),
    ct.c_uint32)(
    ("ts_query_disable_pattern", dll), (
    (1, "self"),
    (1, "pattern_index"),))

# Create a new cursor for executing a given query.
#
# The cursor stores the state that is needed to iteratively search
# for matches. To use the query cursor, first call [`ts_query_cursor_exec`]
# to start running a given query on a given syntax node. Then, there are
# two options for consuming the results of the query:
# 1. Repeatedly call [`ts_query_cursor_next_match`] to iterate over all of the
#    *matches* in the order that they were found. Each match contains the
#    index of the pattern that matched, and an array of captures. Because
#    multiple patterns can match the same set of nodes, one match may contain
#    captures that appear *before* some of the captures from a previous match.
# 2. Repeatedly call [`ts_query_cursor_next_capture`] to iterate over all of the
#    individual *captures* in the order that they appear. This is useful if
#    don't care about which pattern matched, and just want a single ordered
#    sequence of captures.
#
# If you don't care about consuming all of the results, you can stop calling
# [`ts_query_cursor_next_match`] or [`ts_query_cursor_next_capture`] at any point.
#  You can then start executing another query on another node by calling
#  [`ts_query_cursor_exec`] again.
#
query_cursor_new = CFUNC(ct.POINTER(TSQueryCursor))(
    ("ts_query_cursor_new", dll),)

# Delete a query cursor, freeing all of the memory that it used.
#
query_cursor_delete = CFUNC(None,
    ct.POINTER(TSQueryCursor))(
    ("ts_query_cursor_delete", dll), (
    (1, "self"),))

# Start running a given query on a given node.
#
query_cursor_exec = CFUNC(None,
    ct.POINTER(TSQueryCursor),
    ct.POINTER(TSQuery),
    TSNode)(
    ("ts_query_cursor_exec", dll), (
    (1, "self"),
    (1, "query"),
    (1, "node"),))

# Start running a given query on a given node, with some options.
#
query_cursor_exec_with_options = CFUNC(None,
    ct.POINTER(TSQueryCursor),
    ct.POINTER(TSQuery),
    TSNode,
    ct.POINTER(TSQueryCursorOptions))(
    ("ts_query_cursor_exec_with_options", dll), (
    (1, "self"),
    (1, "query"),
    (1, "node"),
    (1, "query_options"),))

# Manage the maximum number of in-progress matches allowed by this query
# cursor.
#
# Query cursors have an optional maximum capacity for storing lists of
# in-progress captures. If this capacity is exceeded, then the
# earliest-starting match will silently be dropped to make room for further
# matches. This maximum capacity is optional — by default, query cursors allow
# any number of pending matches, dynamically allocating new space for them as
# needed as the query is executed.
#
query_cursor_did_exceed_match_limit = CFUNC(ct.c_bool,
    ct.POINTER(TSQueryCursor))(
    ("ts_query_cursor_did_exceed_match_limit", dll), (
    (1, "self"),))
query_cursor_match_limit = CFUNC(ct.c_uint32,
    ct.POINTER(TSQueryCursor))(
    ("ts_query_cursor_match_limit", dll), (
    (1, "self"),))
query_cursor_set_match_limit = CFUNC(None,
    ct.POINTER(TSQueryCursor),
    ct.c_uint32)(
    ("ts_query_cursor_set_match_limit", dll), (
    (1, "self"),
    (1, "limit"),))

# Set the range of bytes in which the query will be executed.
#
# The query cursor will return matches that intersect with the given point range.
# This means that a match may be returned even if some of its captures fall
# outside the specified range, as long as at least part of the match
# overlaps with the range.
#
# For example, if a query pattern matches a node that spans a larger area
# than the specified range, but part of that node intersects with the range,
# the entire match will be returned.
#
# This will return `false` if the start byte is greater than the end byte, otherwise
# it will return `true`.
#
query_cursor_set_byte_range = CFUNC(ct.c_bool,
    ct.POINTER(TSQueryCursor),
    ct.c_uint32,
    ct.c_uint32)(
    ("ts_query_cursor_set_byte_range", dll), (
    (1, "self"),
    (1, "start_byte"),
    (1, "end_byte"),))

# Set the range of (row, column) positions in which the query will be executed.
#
# The query cursor will return matches that intersect with the given point range.
# This means that a match may be returned even if some of its captures fall
# outside the specified range, as long as at least part of the match
# overlaps with the range.
#
# For example, if a query pattern matches a node that spans a larger area
# than the specified range, but part of that node intersects with the range,
# the entire match will be returned.
#
# This will return `false` if the start point is greater than the end point, otherwise
# it will return `true`.
#
query_cursor_set_point_range = CFUNC(ct.c_bool,
    ct.POINTER(TSQueryCursor),
    TSPoint,
    TSPoint)(
    ("ts_query_cursor_set_point_range", dll), (
    (1, "self"),
    (1, "start_point"),
    (1, "end_point"),))

# Set the byte range within which all matches must be fully contained.
#
# Set the range of bytes in which matches will be searched for. In contrast to
# `ts_query_cursor_set_byte_range`, this will restrict the query cursor to only return
# matches where _all_ nodes are _fully_ contained within the given range. Both functions
# can be used together, e.g. to search for any matches that intersect line 5000, as
# long as they are fully contained within lines 4500-5500
#
query_cursor_set_containing_byte_range = CFUNC(ct.c_bool,
    ct.POINTER(TSQueryCursor),
    ct.c_uint32,
    ct.c_uint32)(
    ("ts_query_cursor_set_containing_byte_range", dll), (
    (1, "self"),
    (1, "start_byte"),
    (1, "end_byte"),))

# Set the point range within which all matches must be fully contained.
#
# Set the range of bytes in which matches will be searched for. In contrast to
# `ts_query_cursor_set_point_range`, this will restrict the query cursor to only return
# matches where _all_ nodes are _fully_ contained within the given range. Both functions
# can be used together, e.g. to search for any matches that intersect line 5000, as
# long as they are fully contained within lines 4500-5500
#
query_cursor_set_containing_point_range = CFUNC(ct.c_bool,
    ct.POINTER(TSQueryCursor),
    TSPoint,
    TSPoint)(
    ("ts_query_cursor_set_containing_point_range", dll), (
    (1, "self"),
    (1, "start_point"),
    (1, "end_point"),))

# Advance to the next match of the currently running query.
#
# If there is a match, write it to `*match` and return `true`.
# Otherwise, return `false`.
#
query_cursor_next_match = CFUNC(ct.c_bool,
    ct.POINTER(TSQueryCursor),
    ct.POINTER(TSQueryMatch))(
    ("ts_query_cursor_next_match", dll), (
    (1, "self"),
    (1, "match"),))
query_cursor_remove_match = CFUNC(None,
    ct.POINTER(TSQueryCursor),
    ct.c_uint32)(
    ("ts_query_cursor_remove_match", dll), (
    (1, "self"),
    (1, "match_id"),))

# Advance to the next capture of the currently running query.
#
# If there is a capture, write its match to `*match` and its index within
# the match's capture list to `*capture_index`. Otherwise, return `false`.
#
query_cursor_next_capture = CFUNC(ct.c_bool,
    ct.POINTER(TSQueryCursor),
    ct.POINTER(TSQueryMatch),
    ct.POINTER(ct.c_uint32))(
    ("ts_query_cursor_next_capture", dll), (
    (1, "self"),
    (1, "match"),
    (1, "capture_index"),))

# Set the maximum start depth for a query cursor.
#
# This prevents cursors from exploring children nodes at a certain depth.
# Note if a pattern includes many children, then they will still be checked.
#
# The zero max start depth value can be used as a special behavior and
# it helps to destructure a subtree by staying on a node and using captures
# for interested parts. Note that the zero max start depth only limit a search
# depth for a pattern's root node but other nodes that are parts of the pattern
# may be searched at any depth what defined by the pattern structure.
#
# Set to `UINT32_MAX` to remove the maximum start depth.
#
query_cursor_set_max_start_depth = CFUNC(None,
    ct.POINTER(TSQueryCursor),
    ct.c_uint32)(
    ("ts_query_cursor_set_max_start_depth", dll), (
    (1, "self"),
    (1, "max_start_depth"),))

# ****************** #
# Section - Language #
# ****************** #

# Get another reference to the given language.
#
language_copy = CFUNC(ct.POINTER(TSLanguage),
    ct.POINTER(TSLanguage))(
    ("ts_language_copy", dll), (
    (1, "self"),))

# Free any dynamically-allocated resources for this language, if
# this is the last reference.
#
language_delete = CFUNC(None,
    ct.POINTER(TSLanguage))(
    ("ts_language_delete", dll), (
    (1, "self"),))

# Get the number of distinct node types in the language.
#
language_symbol_count = CFUNC(ct.c_uint32,
    ct.POINTER(TSLanguage))(
    ("ts_language_symbol_count", dll), (
    (1, "self"),))

# Get the number of valid states in this language.
#
language_state_count = CFUNC(ct.c_uint32,
    ct.POINTER(TSLanguage))(
    ("ts_language_state_count", dll), (
    (1, "self"),))

# Get the numerical id for the given node type string.
#
language_symbol_for_name = CFUNC(TSSymbol,
    ct.POINTER(TSLanguage),
    ct.POINTER(ct.c_ubyte),
    ct.c_uint32,
    ct.c_bool)(
    ("ts_language_symbol_for_name", dll), (
    (1, "self"),
    (1, "string"),
    (1, "length"),
    (1, "is_named"),))

# Get the number of distinct field names in the language.
#
language_field_count = CFUNC(ct.c_uint32,
    ct.POINTER(TSLanguage))(
    ("ts_language_field_count", dll), (
    (1, "self"),))

# Get the field name string for the given numerical id.
#
language_field_name_for_id = CFUNC(ct.c_char_p,
    ct.POINTER(TSLanguage),
    TSFieldId)(
    ("ts_language_field_name_for_id", dll), (
    (1, "self"),
    (1, "id"),))

# Get the numerical id for the given field name string.
#
language_field_id_for_name = CFUNC(TSFieldId,
    ct.POINTER(TSLanguage),
    ct.POINTER(ct.c_ubyte),
    ct.c_uint32)(
    ("ts_language_field_id_for_name", dll), (
    (1, "self"),
    (1, "name"),
    (1, "name_length"),))

# Get a list of all supertype symbols for the language.
#
language_supertypes = CFUNC(ct.POINTER(TSSymbol),
    ct.POINTER(TSLanguage),
    ct.POINTER(ct.c_uint32))(
    ("ts_language_supertypes", dll), (
    (1, "self"),
    (1, "length"),))

# Get a list of all subtype symbol ids for a given supertype symbol.
#
# See [`ts_language_supertypes`] for fetching all supertype symbols.
#
language_subtypes = CFUNC(ct.POINTER(TSSymbol),
    ct.POINTER(TSLanguage),
    TSSymbol,
    ct.POINTER(ct.c_uint32))(
    ("ts_language_subtypes", dll), (
    (1, "self"),
    (1, "supertype"),
    (1, "length"),))

# Get a node type string for the given numerical id.
#
language_symbol_name = CFUNC(ct.c_char_p,
    ct.POINTER(TSLanguage),
    TSSymbol)(
    ("ts_language_symbol_name", dll), (
    (1, "self"),
    (1, "symbol"),))

# Check whether the given node type id belongs to named nodes, anonymous nodes,
# or a hidden nodes.
#
# See also [`ts_node_is_named`]. Hidden nodes are never returned from the API.
#
language_symbol_type = CFUNC(TSSymbolType,
    ct.POINTER(TSLanguage),
    TSSymbol)(
    ("ts_language_symbol_type", dll), (
    (1, "self"),
    (1, "symbol"),))

# Get the ABI version number for this language. This version number is used
# to ensure that languages were generated by a compatible version of
# Tree-sitter.
#
# See also [`ts_parser_set_language`].
#
language_abi_version = CFUNC(ct.c_uint32,
    ct.POINTER(TSLanguage))(
    ("ts_language_abi_version", dll), (
    (1, "self"),))

# Get the metadata for this language. This information is generated by the
# CLI, and relies on the language author providing the correct metadata in
# the language's `tree-sitter.json` file.
#
# See also [`TSMetadata`].
#
language_metadata = CFUNC(ct.POINTER(TSLanguageMetadata),
    ct.POINTER(TSLanguage))(
    ("ts_language_metadata", dll), (
    (1, "self"),))

# Get the next parse state. Combine this with lookahead iterators to generate
# completion suggestions or valid symbols in error nodes. Use
# [`ts_node_grammar_symbol`] for valid symbols.
#
language_next_state = CFUNC(TSStateId,
    ct.POINTER(TSLanguage),
    TSStateId,
    TSSymbol)(
    ("ts_language_next_state", dll), (
    (1, "self"),
    (1, "state"),
    (1, "symbol"),))

# Get the name of this language. This returns `NULL` in older parsers.
#
language_name = CFUNC(ct.c_char_p,
    ct.POINTER(TSLanguage))(
    ("ts_language_name", dll), (
    (1, "self"),))

# **************************** #
# Section - Lookahead Iterator #
# **************************** #

# Create a new lookahead iterator for the given language and parse state.
#
# This returns `NULL` if state is invalid for the language.
#
# Repeatedly using [`ts_lookahead_iterator_next`] and
# [`ts_lookahead_iterator_current_symbol`] will generate valid symbols in the
# given parse state. Newly created lookahead iterators will contain the `ERROR`
# symbol.
#
# Lookahead iterators can be useful to generate suggestions and improve syntax
# error diagnostics. To get symbols valid in an ERROR node, use the lookahead
# iterator on its first leaf node state. For `MISSING` nodes, a lookahead
# iterator created on the previous non-extra leaf node may be appropriate.
#
lookahead_iterator_new = CFUNC(ct.POINTER(TSLookaheadIterator),
    ct.POINTER(TSLanguage),
    TSStateId)(
    ("ts_lookahead_iterator_new", dll), (
    (1, "language"),
    (1, "state"),))

# Delete a lookahead iterator freeing all the memory used.
#
lookahead_iterator_delete = CFUNC(None,
    ct.POINTER(TSLookaheadIterator))(
    ("ts_lookahead_iterator_delete", dll), (
    (1, "self"),))

# Reset the lookahead iterator to another state.
#
# This returns `true` if the iterator was reset to the given state and `false`
# otherwise.
#
lookahead_iterator_reset_state = CFUNC(ct.c_bool,
    ct.POINTER(TSLookaheadIterator),
    TSStateId)(
    ("ts_lookahead_iterator_reset_state", dll), (
    (1, "self"),
    (1, "state"),))

# Reset the lookahead iterator.
#
# This returns `true` if the language was set successfully and `false`
# otherwise.
#
lookahead_iterator_reset = CFUNC(ct.c_bool,
    ct.POINTER(TSLookaheadIterator),
    ct.POINTER(TSLanguage),
    TSStateId)(
    ("ts_lookahead_iterator_reset", dll), (
    (1, "self"),
    (1, "language"),
    (1, "state"),))

# Get the current language of the lookahead iterator.
#
lookahead_iterator_language = CFUNC(ct.POINTER(TSLanguage),
    ct.POINTER(TSLookaheadIterator))(
    ("ts_lookahead_iterator_language", dll), (
    (1, "self"),))

# Advance the lookahead iterator to the next symbol.
#
# This returns `true` if there is a new symbol and `false` otherwise.
#
lookahead_iterator_next = CFUNC(ct.c_bool,
    ct.POINTER(TSLookaheadIterator))(
    ("ts_lookahead_iterator_next", dll), (
    (1, "self"),))

# Get the current symbol of the lookahead iterator;
#
lookahead_iterator_current_symbol = CFUNC(TSSymbol,
    ct.POINTER(TSLookaheadIterator))(
    ("ts_lookahead_iterator_current_symbol", dll), (
    (1, "self"),))

# Get the current symbol type of the lookahead iterator as a null terminated
# string.
#
lookahead_iterator_current_symbol_name = CFUNC(ct.c_char_p,
    ct.POINTER(TSLookaheadIterator))(
    ("ts_lookahead_iterator_current_symbol_name", dll), (
    (1, "self"),))

# ********************************* #
# Section - WebAssembly Integration #
# ********************************* #

class wasm_engine_t(ct.Structure): pass
TSWasmEngine = wasm_engine_t
class TSWasmStore(ct.Structure): pass

TSWasmErrorKind = ct.c_int
(
    TSWasmErrorKindNone,  # = 0,
    TSWasmErrorKindParse,
    TSWasmErrorKindCompile,
    TSWasmErrorKindInstantiate,
    TSWasmErrorKindAllocate,

) = range(0, 5)

class TSWasmError(ct.Structure):
    _fields_ = [
    ("kind",    TSWasmErrorKind),
    ("message", ct.c_char_p),
]

# Create a Wasm store.
#
try:  # TREE_SITTER_FEATURE_WASM=OFF
    wasm_store_new = CFUNC(ct.POINTER(TSWasmStore),
        ct.POINTER(TSWasmEngine),
        ct.POINTER(TSWasmError))(
        ("ts_wasm_store_new", dll), (
        (1, "engine"),
        (1, "error"),))
except: pass  # pragma: no cover

# Free the memory associated with the given Wasm store.
#
try:  # TREE_SITTER_FEATURE_WASM=OFF
    wasm_store_delete = CFUNC(None,
        ct.POINTER(TSWasmStore))(
        ("ts_wasm_store_delete", dll), (
        (1, "self"),))
except: pass  # pragma: no cover

# Create a language from a buffer of Wasm. The resulting language behaves
# like any other Tree-sitter language, except that in order to use it with
# a parser, that parser must have a Wasm store. Note that the language
# can be used with any Wasm store, it doesn't need to be the same store that
# was used to originally load it.
#
try:  # TREE_SITTER_FEATURE_WASM=OFF
    wasm_store_load_language = CFUNC(ct.POINTER(TSLanguage),
        ct.POINTER(TSWasmStore),
        ct.c_char_p,
        ct.POINTER(ct.c_ubyte),
        ct.c_uint32,
        ct.POINTER(TSWasmError))(
        ("ts_wasm_store_load_language", dll), (
        (1, "self"),
        (1, "name"),
        (1, "wasm"),
        (1, "wasm_len"),
        (1, "error"),))
except: pass  # pragma: no cover

# Get the number of languages instantiated in the given Wasm store.
#
try:  # TREE_SITTER_FEATURE_WASM=OFF
    wasm_store_language_count = CFUNC(ct.c_size_t,
        ct.POINTER(TSWasmStore))(
        ("ts_wasm_store_language_count", dll), (
        (1, "self"),))
except: pass  # pragma: no cover

# Check if the language came from a Wasm module. If so, then in order to use
# this language with a Parser, that parser must have a Wasm store assigned.
#
language_is_wasm = CFUNC(ct.c_bool,
    ct.POINTER(TSLanguage))(
    ("ts_language_is_wasm", dll), (
    (1, "self"),))

# Assign the given Wasm store to the parser. A parser must have a Wasm store
# in order to use Wasm languages.
#
parser_set_wasm_store = CFUNC(None,
    ct.POINTER(TSParser),
    ct.POINTER(TSWasmStore))(
    ("ts_parser_set_wasm_store", dll), (
    (1, "self"),
    (1, "store"),))

# Remove the parser's current Wasm store and return it. This returns NULL if
# the parser doesn't have a Wasm store.
#
parser_take_wasm_store = CFUNC(ct.POINTER(TSWasmStore),
    ct.POINTER(TSParser))(
    ("ts_parser_take_wasm_store", dll), (
    (1, "self"),))

# ****************************** #
# Section - Global Configuration #
# ****************************** #

# Set the allocation functions used by the library.
#
# By default, Tree-sitter uses the standard libc allocation functions,
# but aborts the process when an allocation fails. This function lets
# you supply alternative allocation functions at runtime.
#
# If you pass `NULL` for any parameter, Tree-sitter will switch back to
# its default implementation of that function.
#
# If you call this function after the library has already been used, then
# you must ensure that either:
#  1. All the existing objects have been freed.
#  2. The new allocator shares its state with the old one, so it is capable
#     of freeing memory that was allocated by the old allocator.
#
set_allocator = CFUNC(None,
    CFUNC(ct.c_void_p, ct.c_size_t),
    CFUNC(ct.c_void_p, ct.c_size_t, ct.c_size_t),
    CFUNC(ct.c_void_p, ct.c_void_p, ct.c_size_t),
    CFUNC(None,        ct.c_void_p))(
    ("ts_set_allocator", dll), (
    (1, "new_malloc"),
    (1, "new_calloc"),
    (1, "new_realloc"),
    (1, "new_free"),))

# eof
